config/routes.rb
Rails.application.routes.draw do

  root :to =>"public/homes#top"

    # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :cooks, only: [:index,:show,:edit,:create,:destroy,:update, :new] do
      resources :cook_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :customers, only: [:index,:show,:edit,:update]
    # 会員側の退会確認画面,退会処理
    get '/customers/:id/quit' => 'customers#quit', as: 'quit'
    patch '/customers/:id/out' => 'customers#out', as: 'out'
  end

  namespace :admin do
    resources :customers, only: [:index, :edit, :update, :show]
    resources :cooks, only: [:index, :show, :destroy] do
      resources :cook_comments, only: [:destroy]  # 管理者側はdestroyのみ
    end
  end

  # 検索機能
  get '/search', to: 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cooks, dependent: :destroy
  has_many :cook_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :nickname, presence: true, length: { maximum: 10 }
  validates :introduction, length: { maximum: 50 }
  validates :email, presence: true

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # 会員検索機能
  def self.search_for(content, method)
    if method == 'perfect'
      Customer.where(nickname: content)
    elsif method == 'forward'
      Customer.where('nickname LIKE ?', content + '%')
    elsif method == 'backward'
      Customer.where('nickname LIKE ?', '%' + content)
    else
      Customer.where('nickname LIKE ?', '%' + content + '%')
    end
  end

  # 退会機能
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # ゲストログイン機能
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
      customer.nickname = "ゲスト"
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @cooks = @customer.cooks.order(created_at: :DESC).page(params[:page])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: "登録情報の変更を保存しました！"
    else
      render "edit", notice: "登録情報の変更に失敗しました"
    end
  end

  private
  # 管理者側は退会ステータスの変更のみ
  def customer_params
    params.require(:customer).permit(:is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_index.html.erb
<div class='container'>
  <table  class='table table-hover table-inverse'>
    <thead>
      <tr class='table-secondary'>
        <th></th>
        <th>会員ID</th>
        <th>ユーザー名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% customers.each do |customer| %>
        <tr>
          <td>
            <%= link_to  admin_customer_path(customer.id) do %>
              <%= image_tag customer.get_profile_image(70, 70) %>
            <% end %>
          </td>
          <td><%= customer.id %></td>
          <td><%= customer.nickname %></td>
          <td><%= customer.email %></td>
            <% if customer.is_deleted? %>
              <td>退会</td>
            <% else %>
              <td>有効</td>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="mt-5 offset-3">
    <%= paginate customers %>
  </div>
</div>

app/views/admin/customers/edit.html.erb
<div class='container'>
    <div class='mt-3'>
      <h3 class='text-nowrap'><%= @customer.nickname %>さんの編集画面</h3>
      <%= form_with model: [:admin, @customer] do |f| %>
        <table class='table table-hover table-inverse'>
          <thead class='table-secondary' height='50'>
            <th scope="col" style="width:50%"></th>
            <th scope="col" style="width:50%"></th>
          </thead>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td class = 'text-nowrap'>ユーザーネーム</td>
            <td><%= @customer.nickname %></td>
          </tr>
          <tr>
            <td>フルネーム</td>
            <td><%= @customer.name %></td>
          </tr>
          <tr>
            <td>プロフィール</td>
            <td><%= @customer.introduction %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>ステータス</td>
            <td>
              <%= f.radio_button :is_deleted, :false %>
              <%= f.label :is_deleted, "有効" %>
              <%= f.radio_button :is_deleted,  :true %>
              <%= f.label :is_deleted, "退会" %>
            </td>
          </tr>
        </table>
        <div class='d-flex justify-content-center my-3'>
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
</div>

app/views/admin/customers/index.html.erb
<div class='mx-auto'>
  <h3 class='offset-2 mt-3 text-nowrap'>会員一覧</h3>
  <%# 会員一覧 %>
  <%= render "admin/customers/index", customers: @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class = 'container'>
  <div class='mt-3'>
    <h3 class='text-nowrap'><%= @customer.nickname %>さんの詳細<%= link_to '編集する', edit_admin_customer_path, class: "btn btn-success btn-sm ml-3" %></h3>
    <table class='table table-hover table-inverse'>
      <thead class='table-secondary' height='50'>
        <th scope="col" style="width:50%"></th>
        <th scope="col" style="width:50%"></th>
      </thead>
      <tbody>
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>ユーザーネーム</td>
          <td><%= @customer.nickname %></td>
        </tr>
        <tr>
          <td>フルネーム</td>
          <td><%= @customer.name %></td>
        </tr>
        <tr>
          <td>プロフィール</td>
          <td><%= @customer.introduction %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>ステータス</td>
          <% if @customer.is_deleted? %>
            <td>退会</td>
          <% else %>
            <td>有効</td>
          <% end %>
        </tr>
      </tbody>
    </table>

    <h3 class='mt-3'><%= @customer.nickname %>さんの投稿一覧</h3>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr class='table-secondary'>
            <th></th>
            <th scope="col" style="width:15%">タイトル</th>
            <th scope="col" style="width:30%">感想</th>
            <th scope="col" style="width:15%">タグ</th>
            <th scope="col" style="width:25%">評価</th>
            <th scope="col" style="width:15%">コメント</th>
        </tr>
      </thead>
      <tbody>
        <% @cooks.each do |cook| %>
          <tr>
            <td><%= image_tag @customer.get_profile_image(70, 70) %></td>
            <td>
              <%= cook.title %><br>
              <%= link_to '詳細', admin_cook_path(cook), class: "cook_#{cook.id} btn btn-success btn-sm mt-3" %>
            </td>
            <td><%= cook.body %></td>
            <td><%= cook.tag %></td>
            <td><%= render "public/cooks/rate", cook: cook %></td>
            <td><%= cook.cook_comments.count %>件</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class='d-flex justify-content-center'>
      <%= paginate @cooks %>
    </div>
  </div>
</div>