config/routes.rb
Rails.application.routes.draw do

  root :to =>"public/homes#top"

    # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :cooks, only: [:index,:show,:edit,:create,:destroy,:update, :new] do
      resources :cook_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :customers, only: [:index,:show,:edit,:update]
    # 会員側の退会確認画面,退会処理
    get '/customers/:id/quit' => 'customers#quit', as: 'quit'
    patch '/customers/:id/out' => 'customers#out', as: 'out'
  end

  namespace :admin do
    resources :customers, only: [:index, :edit, :update, :show]
    resources :cooks, only: [:index, :show, :destroy] do
      resources :cook_comments, only: [:destroy]  # 管理者側はdestroyのみ
    end
  end

  # 検索機能
  get '/search', to: 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cook_comment.rb
class CookComment < ApplicationRecord

  belongs_to :customer
  belongs_to :cook

  validates :comment, length:{maximum:20}, presence: true
end

app/controllers/admin/cook_comments_controller.rb
class Admin::CookCommentsController < ApplicationController
  before_action :authenticate_admin!
  # 管理者側はdestroyのみ
  
  def destroy
    @cook = Cook.find(params[:cook_id])
    @cook_comment = CookComment.find_by(id: params[:id], cook_id: params[:cook_id])
    @cook_comment.destroy
  end

  private

  def cook_comment_params
    params.require(:cook_comment).permit(:comment)
  end

end

app/helpers/cook_comment_helper.rb
module CookCommentHelper
end

app/views/admin/cook_comments/_index.html.erb
<h3>コメント一覧</h3>
<table class="table align-middle table-hover table-inverse">
  <% cook.cook_comments.each do |cook_comment| %>
    <tr>
      <td>
        <%= link_to admin_customer_path(cook_comment.customer) do %>
          <%= image_tag cook_comment.customer.get_profile_image(50, 50) %><br>
        <% end %>
      </td>
      <td><%= cook_comment.customer.nickname %></td>
      <td class = 'pl-5'><%= cook_comment.comment %></td>
      <td><%= link_to "削除", admin_cook_cook_comment_path(cook_comment.cook, cook_comment), method: :delete, remote: true, class: "btn btn-danger btn-sm text-nowrap ml-3" %></td>
    </tr>
  <% end %>
</table>

app/views/admin/cook_comments/destroy.js.erb
$('#admin_comments_area').html("<%= j(render "admin/cook_comments/index",  cook: @cook) %>");