config/routes.rb
Rails.application.routes.draw do

  root :to =>"public/homes#top"

    # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :cooks, only: [:index,:show,:edit,:create,:destroy,:update, :new] do
      resources :cook_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :customers, only: [:index,:show,:edit,:update]
    # 会員側の退会確認画面,退会処理
    get '/customers/:id/quit' => 'customers#quit', as: 'quit'
    patch '/customers/:id/out' => 'customers#out', as: 'out'
  end

  namespace :admin do
    resources :customers, only: [:index, :edit, :update, :show]
    resources :cooks, only: [:index, :show, :destroy] do
      resources :cook_comments, only: [:destroy]  # 管理者側はdestroyのみ
    end
  end

  # 検索機能
  get '/search', to: 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]

    if @model == 'customer'
      @records = Customer.search_for(@content, @method)
    elsif @model == 'cook'
      @records = Cook.search_for(@content, @method)
    elsif @model == 'tag'
      @records = Cook.search_by_tag(@content, @method)
    elsif @model == 'rate'
      @records = Cook.search_by_rate(@content)
    end
    @records = Kaminari.paginate_array(@records).page(params[:page])
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_with url: search_path, method: :get do |f| %>
  <%= f.text_field :content, required: true %>
  <%= f.select :model, options_for_select({ "ユーザー" => "customer", "投稿（タイトル）" => "cook"}) %>
  <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
  <%= f.submit '検索' %>
<% end %>

app/views/searches/_rate_search.html.erb
<%= form_with url: search_path, method: :get do |f| %>
  <%= f.hidden_field :model, value: "rate"  %>
  <%= f.select :content, options_for_select({ "星５" => "5", "星４" => "4", "星３" => "3", "星2" => "2", "星１" => "1"}) %>
  <%= f.submit 'レビューごとに検索' %>
<% end %>

app/views/searches/_tag_form.html.erb
<%= form_with url: search_path, method: :get do |f| %>
  <%= f.text_field :content, required: true %>
  <%= f.hidden_field :model, :value => "tag"  %>
  <%= f.hidden_field :method, :value => "perfect" %>
  <%= f.submit 'タグ検索' %>
<% end %>

app/views/searches/search.html.erb
<% if @model == 'customer' %>
	<h3 class = 'offset-2 mt-5 text-nowrap'>"<%= @content %>"さんの検索結果</h3>
	<% if admin_signed_in? %>
	    <%= render 'admin/customers/index', customers: @records %>
	<% elsif customer_signed_in? %>
	    <%= render 'public/customers/index', customers: @records %>
	<% end %>
  <%#= render 'public/customers/index', customers: @records || 'admin/customers/index', customers: @records %>
<% elsif @model == 'cook' || @model == 'tag' || @model == 'rate' %>
	<h3 class = 'offset-2 mt-5 text-nowrap'>"<%= @content %>"の検索結果</h3>
  <%#= render 'public/cooks/index', cooks: @records || 'admin/cooks/index', cooks: @records %>
  <% if admin_signed_in? %>
      <%= render 'admin/cooks/index', cooks: @records %>
  <% elsif customer_signed_in? %>
      <%= render 'public/cooks/index', cooks: @records %>
  <% end %>
<% end %>