config/routes.rb
Rails.application.routes.draw do

  root :to =>"public/homes#top"

    # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :cooks, only: [:index,:show,:edit,:create,:destroy,:update, :new] do
      resources :cook_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :customers, only: [:index,:show,:edit,:update]
    # 会員側の退会確認画面,退会処理
    get '/customers/:id/quit' => 'customers#quit', as: 'quit'
    patch '/customers/:id/out' => 'customers#out', as: 'out'
  end

  namespace :admin do
    resources :customers, only: [:index, :edit, :update, :show]
    resources :cooks, only: [:index, :show, :destroy] do
      resources :cook_comments, only: [:destroy]  # 管理者側はdestroyのみ
    end
  end

  # 検索機能
  get '/search', to: 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> 件の未記入があります:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="mt-5 mb-3 text-center ">&copy; PiCooking 2022 </p>
</footer>

app/views/layouts/_header.html.erb
<header class="fixed-top bg-dark bg-opacity-75">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">

      <a class="navbar-brand" href="/"><span><%= image_tag('header_logo.png', size: '140x62') %></span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <ul class="navbar-nav ml-auto">

          <% if admin_signed_in? %>
          <%# 管理者でログイン %>

              <div class="my-auto pr-5 mr-5 text-light">
                現在、管理者アカウントでログインしています。
              </div>
              <li>
                <%= link_to admin_cooks_path, class: 'nav-link text-light' do %>
                  投稿一覧
                <% end %>
              </li>
              <li>
                <%= link_to admin_customers_path, class: 'nav-link text-light' do %>
                  会員一覧
                <% end %>
              </li>
              <li>
                <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                  ログアウト
                <% end %>
              </li>
          <% elsif customer_signed_in? %>
          <%# 会員でログイン %>
            <div class="my-auto pr-5 mr-5 text-light">
              ようこそ、<%= current_customer.nickname %>さん！
            </div>
            <li>
              <%= link_to customer_path(current_customer),class: 'nav-link text-light' do %>
                マイページ
              <% end %>
            </li>
            <li>

              <%= link_to new_cook_path, class: 'nav-link text-light' do %>
                投稿する
              <% end %>
            </li>
            <li>
              <%=  link_to customers_path,class: 'nav-link text-light' do %>
                 会員一覧
              <% end %>
            </li>
            <li>
              <%=  link_to cooks_path ,class: 'nav-link text-light' do %>
                 投稿一覧
              <% end %>
            </li>
            <li>
              <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-light' do %>
                 ログアウト
              <% end %>
            </li>
          <% else %>
            <%# ログイン前の状態 %>
            <li>
              <%= link_to root_path,class: 'nav-link text-light' do %>
                 Home
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_registration_path,class: 'nav-link text-light' do %>
                 新規登録
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_session_path ,class: 'nav-link text-light' do %>
                 ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="text-center alert-success"><%= flash[:notice] %></div>
  <div class="text-center alert-danger"><%= flash[:alert] %></div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PiCooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = 'pt-5'>
    <div class = 'pb-5 mb-4'>
      <%= render 'layouts/header' %>
    </div>
    <main>
      <%# ログイン中にのみ検索フォームを表示 %>
      <% if admin_signed_in? || customer_signed_in? %>
        <div class="container">
          <div class="row justify-content-start my-2">
            <div class="mr-5 text-nowrap"><%= render 'searches/form' %></div>
            <div class="mr-3 text-nowrap"><%= render "searches/tag_form" %></div>
            <div class="mr-3 text-nowrap"><%= render "searches/rate_search" %></div>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>